### ISSUE TITLE
How to build kernel and firmware .deb

### ISSUE THREAD

**Issue by alexreinert** [RPi-Distro/repo#104]
Hi,

how can I build the .deb files for kernel and firmware by my own?

Background: I need the fixes for bridging with the lan78xx but for some internal reasons I cannot use rpi-update.

Thanks,
Alex

**Comment by XECDesign** [comment]
I would recommend waiting for the packages to be updated, since we will be releasing them as soon as we're happy that the major issues have been fixed.

If you would like to jump ahead, take a look here https://github.com/RPi-Distro/firmware/blob/debian/debian/update.sh. It's quite a mess and I wouldn't recommend it.

**Comment by alexreinert** [comment]
Thanks a lot, this helps me.
