### ISSUE TITLE
Welcome tool restricts Language per Country

### ISSUE THREAD

**Issue by kenfallon** [RPi-Distro/repo#108]
In the welcome application "Set Country" page with the text "Enter the details of your location. This is used to set language time zone, keyboard and other international settings."

Selecting a Country restricts the user to a drop-down list of languages, and provides no option to add other languages. This selection incorrectly assumes that the only languages that people use in a given region are those with official language status. It fails to consider the diversity of the populations, and the fact that people may wish to use a non default language.

As an example, the country of Ireland only gives the option of English and Irish languages, while the 2011 national census shows a total of 182 different languages in use. It continues to say "As already reported in This Is Ireland, Part 1: 514,068 residents spoke a language other than Irish or English at home in 2011." Given ROI has a population of 4,792,500 this represents 10% of the install base that may wish to select an install language other than Irish or English.
https://en.wikipedia.org/wiki/Republic_of_Ireland#cite_note-145

The same extends to the Netherlands where we are restricted to Dutch, Limburgish, Low Saxon, and West Frisian. Despite 22.61% of the residents been described as non Dutch. Even then there is a sizable population of Dutch speakers that prefer to install English operating systems for one reason or another.

Please change this so that there is always the option to add another language not in the official list.

**Comment by XECDesign** [comment]
The full set of options can be accessed through the configuration utility (Menu->Preferences->Raspberry Pi Configuration). The first run wizard doesn't try to cover every possible scenario.

**Comment by Ferroin** [comment]
Not offering a usable language on the first run is a _BIG_ UX problem on a pretty binary level.  That is, this fails the grandmother test to a degree that's it's make-or-break behavior.

I'd suggest updating it to work in the opposite order of what it does now.  Select a language, and then pick a locale (with the option to select whatever the default locale for the language is.  That brings it a bit more in-line with how most other Linux platforms handle this, and also makes it exponentially less likely that regular users will not have issues getting things set up.

**Comment by spl237** [comment]
The restrictions here are nothing to do with the Raspberry Pi wizard - they are inherent in Linux's internationalisation support.

In Linux, the basic setting for internationalisation is called a locale. A locale is a combination of a country and a language used in that country. In Debian, there are around 250 valid locales defined; this is to cover around 100 languages, and around 100 countries. Simple mathematics will show that Debian does not, therefore, allow you to select any language for any country - to do so would require there to be 10,000 valid locales rather than the 250 or so there actually are.

The wizard shows all languages for each country for which there is a valid locale file in Debian. Unless people decide to add additional locales to Debian, there is no way to offer other combinations via the wizard - or by any other method.

For what it is worth, the way Debian does this - selecting language first and then country - makes very little sense to me, and I have opted to do it the other way around. But this has not reduced the list of available language and country combinations in any way. If you want to select a language and country combination which is not offered by the wizard, feel free to submit a patch to Debian upstream with the new locale file you have created...

**Comment by Ferroin** [comment]
@spl237 I know absolutely how it all works at a low level.  I'm that crazy guy who's using 3 different locales simultaneously just to get dates and numbers to display the way I want while keeping my preferred language.  That changes exactly nothing about the primary issue here, which is that the order things are being done in is bad UX.  There's a _reason_ that pretty much every distribution in existence does it the other way around, or lets you select both on the same screen as dropdowns, or just gives you an actual locale list. It's quite simply better UX for people who are not computer literate.  Hell, it's still better even for people who _are_ computer literate, because people don't memorize what countries have what languages for locale (well, most people don't, I'm one of the exceptions here too, though I by no means have all of them memorized).  It's especially important for people coming from a Windows background though, because language and region are not tied together like this there.

Looking at this logically, for people who speak a language not covered by their country's locale options:

* If the country is selected first, the reaction is likely to be something along the lines of 'Wait, what, I don't want to use _any_ of these languages, just let me pick one I want!'.  They then either have to go back to pick a country that does list the language they speak (which may be non-trivial), or they have to continue through the rest of setup in what is most likely not their native language.
* If the language is selected first, their reaction to not seeing their country of residence is more likely to be along the lines of 'OK, why is it not here?  I guess I'll just pick the nearest country that's listed here.'.  Boom, done, no need to go back to country selection at all, and they can finish setup in their native language.

**Comment by spl237** [comment]
I can see your point, but I disagree with this:

> They then either have to go back to pick a country that does list the language they speak (_which may be non-trivial_)

I find it very hard to believe that someone could want a language and not know a country in which it is spoken. People are not going to struggle to find the language they want to use - in 99% of cases, it will be the one for the country they select. If it isn't, then they will know a country where that language is spoken - for example, if you want English, it isn't rocket science to know that you choose the UK or the USA.

For me, it is far more logical to select a country, and then the specific language spoken in that country - that is the way internationalisation works on Macs and Windows; you select country first, and I'm afraid they represent better UX design than Linux in most cases!

**Comment by Ferroin** [comment]
> I find it very hard to believe that someone could want a language and not know a country in which it is spoken.

Never underestimate human stupidity.  Things that may seem 'obvious' to one person may be completely unknown to others.  See for example the fact that Afrikaans is a Germanic language.

>  If it isn't, then they will know a country where that language is spoken - for example, if you want English, it isn't rocket science to know that you choose the UK or the USA.

But can you name any others beyond Australia and New Zealand where it's spoken _without looking at locales_?  That said, English, like most Indo-European languages, is a bad example, they're sufficiently widespread that you've got a decent chance of picking a country at random and finding them (there's about a dozen or more English locales, so you've got a roughly 5% chance of picking a country at random that has an English locale).  Try Yiddish as an example that's non-trivial to figure out a country for, it's spoken as a secondary language in pretty significant percentage countries in the world, but there's only one locale for it.

> For me, it is far more logical to select a country, and then the specific language spoken in that country - that is the way internationalisation works on Macs and Windows; you select country first, and I'm afraid they represent better UX design than Linux in most cases!

'But everyone else does it this way!' isn't a good argument unless you can substantiate _why_ everyone else does it that way.  On Windows, it's irrelevant, because they don't tie together language and region (the settings are co-located because they logically go together, but they are not strictly dependent on each other like they are on most UNIX systems).  As far as macOS, I can't really comment much, but I've heard from a couple of people that they aren't exactly the best when it comes to localization.

**Comment by spl237** [comment]
> But can you name any others beyond Australia and New Zealand where it's spoken without looking at locales?

Yes, several - off the top of my head, Ireland, Canada, South Africa, Hong Kong, various Caribbean states (Antigua, Barbados, Bermuda etc.) - want me to go on? ;)

> Try Yiddish as an example that's non-trivial to figure out a country for, it's spoken as a secondary language in pretty significant percentage countries in the world, but there's only one locale for it.

What percentage of users do you honestly think want to use Yiddish as the language on their Pi - a language for which the actual number of translation files relevant for our desktop is as close to zero as makes no odds - and are not in the country where it is spoken? The whole point of the wizard, as I have said repeatedly, is to make life easier for the majority of users - it is not intended to cover every obscure corner case. (And Yiddish as an expatriate is pretty much the definition of a "corner case", in this situation!)

> 'But everyone else does it this way!' isn't a good argument unless you can substantiate why everyone else does it that way.

In UI design, "everyone else does it this way" is the best argument there is for doing something. People's expectations are set by what they have seen before. You need a very good argument for doing something a different way from how everyone else does it; you need no argument at all for doing things the way people are used to; "that's the way everyone else does it" is all you need. "Do what people expect" is pretty much the first rule of UI design.

I reiterate - the wizard is intended to make it easier for 90% of users to configure a brand-new Pi. It is not intended - and nor will it ever be intended - to cover every possible unusual configuration. For that, people will need to use the other mechanisms which are all in place for locale setting, including the locale box in Raspberry Pi Configuration, which does follow the Linux approach of setting language first. (One of the main reasons the wizard exists is because setting language first seems counterintuitive to me...)

**Comment by Ferroin** [comment]
> Yes, several - off the top of my head, Ireland, Canada, South Africa, Hong Kong, various Caribbean states (Antigua, Barbados, Bermuda etc.) - want me to go on? ;)

Now think for a moment about how long you had to think about that.  Then think about how long you would have to think about that if you were a 12 year old trying to set up your first computer with no knowledge whatsoever of linguistic distribution of your preferred language.

> What percentage of users do you honestly think want to use Yiddish as the language on their Pi - a language for which the actual number of translation files relevant for our desktop is as close to zero as makes no odds - and are not in the country where it is spoken? The whole point of the wizard, as I have said repeatedly, is to make life easier for the majority of users - it is not intended to cover every obscure corner case. (And Yiddish as an expatriate is pretty much the definition of a "corner case", in this situation!)

The point is that such cases do exist.  Also, _EVERY_ Yiddish speaker is an expatriate technically.  There is no 'home' country for it, unless you count Israel, which is not entirely accurate.

> In UI design, "everyone else does it this way" is the single best argument there is for doing something. People's expectations are set by what they have seen before. You need a very good argument for doing something a different way from how everyone else does it; you need no argument at all for doing things the way people are used to; "that's the way everyone else does it" is all you need. "Do what people expect" is pretty much the first rule of UI design (along with its obvious corollary - "don't do what people don't expect").

Yes, but does this actually impact user expectations?  I mean, do you seriously think it's going to confuse a user to have to pick a language before picking what country they are located in?  Even aside from that, you're missing the one _big_ caveat to this rule, that doing things in a more sensible manner than what people expect is rarely ever a bad thing (think about how painful it would be to work with Wine if it randomly pulled crap like trying to change DPI settings for your apps like Windows 10 does now if it thinks they aren't scaling right).

> I reiterate - the wizard is intended to make it easier for 90% of users to configure a brand-new Pi. It is not intended - and nor will it ever be intended - to cover every possible unusual configuration. For that, people will need to use the other mechanisms which are all in place for locale setting, including the locale box in Raspberry Pi Configuration, which does follow the Linux approach of setting language first. (And hence is one of the main reasons the wizard exists, because setting language first seems counterintuitive to me...)

Imagine you speak not a single word of English.  At all (and no, this is _not_ a corner case, hard as it may be to believe).  Would you rather have to sit through deciphering the first few screens of an installer before you switch things to a language you know, or would you rather just pick it first thing?

The Windows and Mac approach works because when you buy one in a given country, the _installer_ is by default localized for that country's primary language (see for example the fact that Microsoft provides pre-localized install disks for pretty much every language they support, and they key them by _language_, not _region_).  So, for a vast majority of cases, users are likely to at least have a basic understanding of the installer language.  This is the other reason that Linux distributions do things the way they do, they don't provide installers that are localized from the moment they start, so they make sure the user can pick their language immediately and doesn't have to suffer through trying to understand a language they may not know.  Just like Linux distributions, there appears to be no pre-localized version of the setup wizard, so it makes more sense to to have the language selection first.
