### ISSUE TITLE
Monday 15-8-2022 libldb2, python3-ldb and ldb-tools update broke samba-ad-dc.service

### ISSUE THREAD

**Issue by antoniosk** [RPi-Distro/repo#305]
After updating the aforementioned packages to the newer versions shown below...

libldb2:armhf 2:2.2.3-2~deb11u1 ==> 2:2.2.3-2~deb11u2
python3-ldb:armhf 2:2.2.3-2~deb11u1 ==> 2:2.2.3-2~deb11u2
ldb-tools:armhf 2:2.2.3-2~deb11u1 ==> 2:2.2.3-2~deb11u2

...via apt-get on a secondary Samba AD DC 2:4.13.13+dfsg-1~deb11u4 running Raspbian Bullseye on a Rpi2B, the samba-ad-dc.service fails to start and exits with error "exit_daemon: daemon failed to start: Samba failed to prime database, error code 22".

I can't confirm if this is also a Debian Bullseye problem. However, Debian package list on https://packages.debian.org/ does not have a "deb11u2" version for any of libldb2, python3-ldb or ldb-tools.

While the updates are postponed for the rest Rpi based DCs, is there a safe way to downgrade those packages on the affected DC?

**Comment by XECDesign** [comment]
This isn't a package we've made any changes to and the version you're seeing seems to match what's in Debian:
https://tracker.debian.org/pkg/ldb
https://tracker.debian.org/news/1353618/accepted-ldb-2223-2deb11u2-source-into-stable-security-embargoed-stable-security/

Since it's not one of our packages, the issue should be reported either to Raspbian or Debian, depending on whether the problem appears in Debian.
